# Generated by Django 4.2.6 on 2023-11-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pypdbObject',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
