# Generated by Django 4.2.6 on 2023-11-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pypdbobject',
            name='description',
        ),
        migrations.AddField(
            model_name='pypdbobject',
            name='authors',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pypdbobject',
            name='doi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pypdbobject',
            name='pubmed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pypdbobject',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='pypdbobject',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
