# Generated by Django 4.2.6 on 2023-10-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('chain', models.CharField(max_length=120)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
